### PR TITLE
use smaller base image

### PR DESCRIPTION
**Pull request by liangchenye**
Signed-off-by: Liang Chenye <liangchenye@huawei.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
Hi @odidev , this is a smaller one, can you help to do a simple test in your environment?

**Comment by odidev** [comment]
Hi @liangchenye,

I just checked with your rootfs, and I can notice that ```\etc\yum.repos.d``` is empty.
This means that there are **No** ```yum```  repositories in the rootfs.

Is this something desired behaviour?

Regards,

**Comment by liangchenye** [comment]
@no, it is not intended, I'll update it.

**Comment by odidev** [comment]
Thanks, @liangchenye 
Then, I will wait for PR update.

**Comment by liangchenye** [comment]
force updated, PTAL @odidev

**Comment by odidev** [comment]
Hi @liangchenye 

I checked with your rootfs.
Yes, your rootfs and changes are working **pretty well** in my test environment too.

I think we can go ahead with your image to support ```aarch64``` for ```EulerOS```.

Regards

**Comment by liangchenye** [comment]
Cool, will you check in this PR ? @odidev

**Comment by odidev** [comment]
@liangchenye 
I am sorry, I didn't get you.
But yes, I already checked the rootfs given by you in this PR and it is working fine.

**Comment by liangchenye** [comment]
I mean ,you can check in my PR in https://github.com/odidev/euleros-docker-images/pull/1
And I will update your PR in  https://github.com/euleros/euleros-docker-images then.

**Comment by odidev** [comment]
I am sorry @liangchenye 
I think there is still some misunderstanding at my end,
Are you are saying that 
- Option 1 : I should merge this PR in this forked repository and then you will take it ahead
- Option 2: I should update my already raised PR (https://github.com/euleros/euleros-docker-images/pull/11) with your changes and then you will merge that PR.

Please guide accordingly as I don't want to mess up all the efforts doen by you and me.

Regards,

**Comment by liangchenye** [comment]
option1  :)

I think when you merge this PR, the PR to euleros#11 will updated automaticly.

**Comment by odidev** [comment]
Done 😄 
Thanks, @liangchenye for your support.

**Pull request merged**
